/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package editor;

import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Font;
import java.awt.event.KeyEvent;

/**
 *
 * @author hellb
 */
public class Editor extends javax.swing.JFrame {

    /**
     * Creates new form Editor
     */
    public Editor() {
        initComponents();
        
        this.txtCodigo.setTabSize(4);
        this.txtCodigo.setFont(new Font("Consolas", Font.PLAIN, 14));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        panelArbolArchivos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jLabel1 = new javax.swing.JLabel();
        panelCodigo = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtCodigo = new javax.swing.JTextArea();
        panelFasesCompilacion = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtLexico = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtSintactico = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtSemantico = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtCodigoIntermedio = new javax.swing.JTextArea();
        panelOutput = new javax.swing.JTabbedPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtErrores = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtResultados = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnArchivo = new javax.swing.JMenu();
        mnOpNuevo = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnOpAbrir = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnOpGuardar = new javax.swing.JMenuItem();
        mnOpGuardarTodo = new javax.swing.JMenuItem();
        mnOpGuardarComo = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnOpSalir = new javax.swing.JMenuItem();
        mnEditar = new javax.swing.JMenu();
        mnFormato = new javax.swing.JMenu();
        mnCompilar = new javax.swing.JMenu();
        mnAyuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IDE");
        setMinimumSize(new java.awt.Dimension(1200, 700));

        bg.setMinimumSize(new java.awt.Dimension(1200, 700));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelArbolArchivos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(jTree1);

        panelArbolArchivos.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 190, 470));

        jLabel1.setText("Proyectos");
        panelArbolArchivos.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        bg.add(panelArbolArchivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 190, 500));

        txtCodigo.setColumns(20);
        txtCodigo.setRows(5);
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(txtCodigo);

        panelCodigo.addTab("tab1", jScrollPane3);

        bg.add(panelCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 630, 500));

        txtLexico.setColumns(20);
        txtLexico.setRows(5);
        jScrollPane2.setViewportView(txtLexico);

        panelFasesCompilacion.addTab("Lexico", jScrollPane2);

        txtSintactico.setColumns(20);
        txtSintactico.setRows(5);
        jScrollPane6.setViewportView(txtSintactico);

        panelFasesCompilacion.addTab("Sintáctico", jScrollPane6);

        txtSemantico.setColumns(20);
        txtSemantico.setRows(5);
        jScrollPane7.setViewportView(txtSemantico);

        panelFasesCompilacion.addTab("Semántico", jScrollPane7);

        txtCodigoIntermedio.setColumns(20);
        txtCodigoIntermedio.setRows(5);
        jScrollPane8.setViewportView(txtCodigoIntermedio);

        panelFasesCompilacion.addTab("Código Intermedio", jScrollPane8);

        bg.add(panelFasesCompilacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, 340, 500));

        txtErrores.setColumns(20);
        txtErrores.setRows(5);
        jScrollPane4.setViewportView(txtErrores);

        panelOutput.addTab("Errores", jScrollPane4);

        txtResultados.setColumns(20);
        txtResultados.setRows(5);
        jScrollPane5.setViewportView(txtResultados);

        panelOutput.addTab("Resultados", jScrollPane5);

        bg.add(panelOutput, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 1180, 180));

        mnArchivo.setText("Archivo");

        mnOpNuevo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnOpNuevo.setText("Nuevo");
        mnArchivo.add(mnOpNuevo);
        mnArchivo.add(jSeparator2);

        mnOpAbrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnOpAbrir.setText("Abrir");
        mnArchivo.add(mnOpAbrir);
        mnArchivo.add(jSeparator3);

        mnOpGuardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnOpGuardar.setText("Guardar");
        mnOpGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnOpGuardarActionPerformed(evt);
            }
        });
        mnArchivo.add(mnOpGuardar);

        mnOpGuardarTodo.setText("Guardar todo");
        mnArchivo.add(mnOpGuardarTodo);

        mnOpGuardarComo.setText("Guardar como...");
        mnArchivo.add(mnOpGuardarComo);
        mnArchivo.add(jSeparator1);

        mnOpSalir.setText("Salir");
        mnArchivo.add(mnOpSalir);

        jMenuBar1.add(mnArchivo);

        mnEditar.setText("Editar");
        jMenuBar1.add(mnEditar);

        mnFormato.setText("Formato");
        jMenuBar1.add(mnFormato);

        mnCompilar.setText("Compilar");
        jMenuBar1.add(mnCompilar);

        mnAyuda.setText("Ayuda");
        jMenuBar1.add(mnAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnOpGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnOpGuardarActionPerformed
        if(!this.txtCodigo.getText().isBlank()){
            this.txtResultados.setText(this.txtCodigo.getText());
        }
    }//GEN-LAST:event_mnOpGuardarActionPerformed

    private void txtCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyReleased
        cerrarCaracter(evt.getKeyChar());
    }//GEN-LAST:event_txtCodigoKeyReleased
    
    private void cerrarCaracter(char caracter){
        if(caracter == 40 | caracter == 91 | caracter == 123 ){
            int ascii = caracter + 1 * (caracter%2 + 1);
            this.txtCodigo.insert(String.valueOf((char) ascii), this.txtCodigo.getCaretPosition());
            this.txtCodigo.setCaretPosition(this.txtCodigo.getCaretPosition() - 1);
        }else if( caracter == 34 | caracter == 39 ){
            this.txtCodigo.insert(String.valueOf(caracter), this.txtCodigo.getCaretPosition());
            this.txtCodigo.setCaretPosition(this.txtCodigo.getCaretPosition() - 1);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {       
        FlatDarkLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Editor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JTree jTree1;
    private javax.swing.JMenu mnArchivo;
    private javax.swing.JMenu mnAyuda;
    private javax.swing.JMenu mnCompilar;
    private javax.swing.JMenu mnEditar;
    private javax.swing.JMenu mnFormato;
    private javax.swing.JMenuItem mnOpAbrir;
    private javax.swing.JMenuItem mnOpGuardar;
    private javax.swing.JMenuItem mnOpGuardarComo;
    private javax.swing.JMenuItem mnOpGuardarTodo;
    private javax.swing.JMenuItem mnOpNuevo;
    private javax.swing.JMenuItem mnOpSalir;
    private javax.swing.JPanel panelArbolArchivos;
    private javax.swing.JTabbedPane panelCodigo;
    private javax.swing.JTabbedPane panelFasesCompilacion;
    private javax.swing.JTabbedPane panelOutput;
    private javax.swing.JTextArea txtCodigo;
    private javax.swing.JTextArea txtCodigoIntermedio;
    private javax.swing.JTextArea txtErrores;
    private javax.swing.JTextArea txtLexico;
    private javax.swing.JTextArea txtResultados;
    private javax.swing.JTextArea txtSemantico;
    private javax.swing.JTextArea txtSintactico;
    // End of variables declaration//GEN-END:variables
}
